// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const useAzureAuth = import.meta.env.VITE_USE_AZURE_AUTH === 'true';
const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL || '').trim();
const SUPABASE_PUBLISHABLE_KEY = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '').trim();

// When using Azure auth without Supabase, avoid createClient() requiring a real URL (module is still imported elsewhere)
const url = useAzureAuth && !SUPABASE_URL ? 'https://placeholder.supabase.co' : SUPABASE_URL;
const key = useAzureAuth && !SUPABASE_PUBLISHABLE_KEY ? 'placeholder' : SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(url, key, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});